# Generated by Django 5.1.4 on 2025-01-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_note_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(),
        ),
    ]
